apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-cronjob
  namespace: project
spec:
  schedule: "0 * * * *"  # Every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-cron
            image: dockersifath/todo-cron:2.9.5
            env:
              - name: BACKEND_URL
                value: "http://todo-backend-service:3002/todos"
          restartPolicy: OnFailure
