apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: dockersifath/log-output:2.5
          ports:
            - containerPort: 3000
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-config
                  key: MESSAGE
          volumeMounts:
            - name: config-volume
              mountPath: /app/config  # Change to your app's expected path
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: log-config
            items:
              - key: information.txt
                path: information.txt

