apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
spec:
  type: NodePort
  selector:
    app: log-output
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002  # You can now access from browser via localhost:30002

