apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
    - port: 3000          # The port the service exposes inside the cluster
      targetPort: 3000    # The port your app listens on
      protocol: TCP
