apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: dockersifath/todo-app
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: BACKEND_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: PORT
          volumeMounts:
            - name: todo-storage
              mountPath: /app/storage
      volumes:
        - name: todo-storage
          persistentVolumeClaim:
            claimName: todo-app-pvc

