apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
  - configmap.yaml
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: dockersifath/todo-app
    newTag: "3.5.1"
