apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual           # <- add this line
  persistentVolumeReclaimPolicy: Retain  # recommended for manual PVs
  hostPath:
    path: /tmp/todo-cache

