apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-pvc
  namespace: project
spec:
  volumeName: todo-pv               # explicit binding to PV named todo-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual          # <- must match PV's storageClassName

