apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: dockersifath/todo-app:latest
          ports:
            - containerPort: 4444
          env:
            - name: PORT
              value: "4444"
