apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: dockersifath/todo-backend:2.6.1  # match your image tag here
          ports:
            - containerPort: 3002  # match your app listening port here
          env:
            - name: PORT
              value: "3002"

