apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
  namespace: project
spec:
  type: NodePort
  selector:
    app: todo-backend
  ports:
    - port: 3002
      targetPort: 3002
      #nodePort: 30002
