apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-deployment
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: dockersifath/pingpong:4.1.1
          ports:
            - containerPort: 3001
          env:
            # Use the StatefulSet's stable pod DNS through the headless service
            - name: PGHOST
              value: "postgres-sts-0.postgres-svc"
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_DB
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5

