apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: pingpong
  ports:
    - port: 80        # service port
      targetPort: 3001 # container port

