apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: exercises
spec:
  type: LoadBalancer        # GKE will allocate external IP
  selector:
    app: pingpong
  ports:
    - port: 3001
      targetPort: 3001

